dhcp-match=set:bios,option:client-arch,0
dhcp-match=set:uefi-x64,option:client-arch,7
dhcp-match=set:uefi-x64,option:client-arch,8
dhcp-match=set:uefi-x64,option:client-arch,9
dhcp-match=set:uefi-arm64,option:client-arch,b

#dhcp-pxe-vendor=HTTPClient

#pxe-service=tag:uefi-arm64,arm64_EFI,"Network Boot"

dhcp-boot=tag:bios,pxelinux.0

dhcp-boot=tag:uefi-x64,boot/grub2/x86_64-efi/core.efi

dhcp-boot=tag:uefi-arm64,boot/grub2/arm64-efi/core.efi,netsrv,10.0.0.250
#dhcp-boot=tag:uefi-arm64,boot/ipxe/arm64-efi/ipxe.efi
#dhcp-boot=tag:uefi-arm64,uefi/grubaa64.efi
#dhcp-boot=tag:uefi-arm64,uefi/shimaa64.efi
#dhcp-boot=tag:uefi-arm64,"http://10.0.0.250:8080/rhel10/rhel-10.0-beta-aarch64-boot.iso"

#dhcp-option-force=tag:uefi-arm64,option:vendor-class,HTTPClient

dhcp-option=option:ntp-server,0.0.0.0

